### ISSUE TITLE
Can't Round Trip Instant using default serializers

### ISSUE THREAD

**Issue by thegreatco** [nodatime/nodatime.serialization#20]
Here is a simple repro

```
[Test]
public void Deserialize_ToNonNullableType_InClass()
{
    var instantInAClass = new InstantTestClass() {Now = SystemClock.Instance.GetCurrentInstant()};
    var json = JsonConvert.SerializeObject(instantInAClass);
    var deserializedInstantInAClass = JsonConvert.DeserializeObject<InstantTestClass>(json, settings);
    var expectedInstant = instantInAClass.Now;
    Assert.AreEqual(expectedInstant, deserializedInstantInAClass.Now);
}

private class InstantTestClass
{
    public Instant Now { get; set; }
}
```

Expected output is the `Assert.AreEqual` succeeding. Actual output is an exception 😢 
```
NodaTime.Utility.InvalidNodaDataException : Unexpected token parsing Instant. Expected String, got StartObject.
   at NodaTime.Serialization.JsonNet.NodaPatternConverter`1.ReadJsonImpl(JsonReader reader, JsonSerializer serializer)
   at NodaTime.Serialization.JsonNet.NodaConverterBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at NodaTime.Serialization.Test.JsonNet.NodaInstantConverterTest.Deserialize_ToNonNullableType_InClass()
```

**Comment by jskeet** [comment]
You haven't shown `settings`, but I'm assuming that's the `JsonSerializerSettings` that's configured for Noda Time. You're passing that into `DeserializeObject` but not into `SerializeObject`.

Just change the second line to

```csharp
var json = JsonConvert.SerializeObject(instantInAClass, settings);
```

and I'd expect it to be fine.

**Comment by thegreatco** [comment]
Doh! You're right. This was an admittedly rushed attempt at a repro for a problem I have in my code. I do provide the settings on both deserialize and serialize (checked in the debugger to see the converter is registered) but I can't get the instant to round trip. I'll update with more information in the morning.

**Comment by jskeet** [comment]
Okay, we'll leave the issue open for the moment. Good luck reproducing it. (Does it surface in the same way in your real code, or does it deserialize, but lose information?)

**Comment by thegreatco** [comment]
Ok, this is the error I get, using a sample program written in LINQPad.

```
void Main()
{
	try
	{
		var jsonSettings = new JsonSerializerSettings();
		jsonSettings.Converters.Add(NodaConverters.InstantConverter);

		var foo = new InstantTestClass() { Now = SystemClock.Instance.GetCurrentInstant() };
		var json = JsonConvert.SerializeObject(foo, jsonSettings);
		Console.WriteLine(json);
		var newJson = JsonConvert.DeserializeObject<InstantTestClass>(json, jsonSettings);
		Console.WriteLine(newJson);
	}
	catch(Exception ex)
	{
		Console.WriteLine(ex.ToString());
	}
}

// Define other methods and classes here
public class InstantTestClass
{
	public Instant Now {get;set;}
}
```

The output is
```
{"Now":"2018-03-07T15:28:51.0033534Z"}
NodaTime.Utility.InvalidNodaDataException: Unexpected token parsing Instant. Expected String, got Date.
   at NodaTime.Serialization.JsonNet.NodaPatternConverter`1.ReadJsonImpl(JsonReader reader, JsonSerializer serializer)
   at NodaTime.Serialization.JsonNet.NodaConverterBase`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at UserQuery.Main() in C:\Users\<user>\AppData\Local\Temp\LINQPad5\_psvxrofa\query_xyushf.cs:line 44
```

The exception is slightly different than what my original test generated.

Versions in use:
Json.NET: 11.0.1
NodaTime: 2.2.4
NodaTime.Serialization.JsonNet: 2.0.0

**Comment by jskeet** [comment]
The problem there is that you're just adding the InstantConverter without disabling Json.NET's own Date handling.

If you call the `ConfigureForNodaTime` extension method instead, it should work - or you can do it yourself here:

```csharp
jsonSettings.DateParseHandling = DateParseHandling.None;
```

**Comment by thegreatco** [comment]
👍 That fixed it! Thanks @jskeet for such a fast response.

**Comment by jskeet** [comment]
Phew - glad it wasn't an actual bug :)
